name: "Release"
on:
  push:
  pull_request:

jobs:
  windows:
    name: Build Windows Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.81.0
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: script/build-windows.sh
