name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  windows:
    name: Build Windows Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.81.0
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: script/build-windows.sh "${{ github.ref_name }}"
      - name: Rename installer
        run: cp windows/Output/rscc-installer.exe rscc-windows-installer-x86_64-${{ github.ref_name }}.exe
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: rscc-windows-installer-x86_64-${{ github.ref_name }}.exe
      - name: Rename artifact
        run: cp rscc-windows.tar.gz rscc-windows-gnu-x86_64-${{ github.ref_name }}.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: rscc-windows-gnu-x86_64-${{ github.ref_name }}.tar.gz
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    needs:
      - windows
    steps:
      - uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: "true"
          files: |
            windows-installer/rscc-windows-installer-x86_64-${{ github.ref_name }}.exe
            windows-artifact/rscc-windows-gnu-x86_64-${{ github.ref_name }}.tar.gz
