
name: Test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.81.0
    - name: Run tests
      run: cargo test
